/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ACheckboxGroup: typeof import('ant-design-vue/es')['CheckboxGroup']
    AConfigProvider: typeof import('ant-design-vue/es')['ConfigProvider']
    ADropdown: typeof import('ant-design-vue/es')['Dropdown']
    AEmpty: typeof import('ant-design-vue/es')['Empty']
    AForm: typeof import('ant-design-vue/es')['Form']
    AFormItem: typeof import('ant-design-vue/es')['FormItem']
    AInput: typeof import('ant-design-vue/es')['Input']
    AMenu: typeof import('ant-design-vue/es')['Menu']
    AMenuDivider: typeof import('ant-design-vue/es')['MenuDivider']
    AMenuItem: typeof import('ant-design-vue/es')['MenuItem']
    APagination: typeof import('ant-design-vue/es')['Pagination']
    ASelect: typeof import('ant-design-vue/es')['Select']
    ASpin: typeof import('ant-design-vue/es')['Spin']
    ATable: typeof import('ant-design-vue/es')['Table']
    ATag: typeof import('ant-design-vue/es')['Tag']
    ATextarea: typeof import('ant-design-vue/es')['Textarea']
    ATimeline: typeof import('ant-design-vue/es')['Timeline']
    ATimelineItem: typeof import('ant-design-vue/es')['TimelineItem']
    ATooltip: typeof import('ant-design-vue/es')['Tooltip']
    ATransfer: typeof import('ant-design-vue/es')['Transfer']
    BAlert: typeof import('./src/components/base/BasicComponents/BModal/BAlert.vue')['default']
    BaseLoading: typeof import('./src/components/base/BasicComponents/BLoading/BaseLoading.vue')['default']
    BButton: typeof import('./src/components/base/BasicComponents/BButton.vue')['default']
    BCard: typeof import('./src/components/base/BasicComponents/BCard.vue')['default']
    BCheckbox: typeof import('./src/components/base/BasicComponents/BCheckbox.vue')['default']
    BForm: typeof import('./src/components/base/BasicComponents/BForm/BForm.vue')['default']
    BInput: typeof import('./src/components/base/BasicComponents/BInput.vue')['default']
    BList: typeof import('./src/components/base/BasicComponents/BList.vue')['default']
    BLoading: typeof import('./src/components/base/BasicComponents/BLoading.vue')['default']
    BModal: typeof import('./src/components/base/BasicComponents/BModal/BModal.vue')['default']
    BRadio: typeof import('./src/components/base/BasicComponents/BRadio.vue')['default']
    BSelect: typeof import('./src/components/base/BasicComponents/BSelect.vue')['default']
    BSpace: typeof import('./src/components/base/BasicComponents/BSpace.vue')['default']
    BTabs: typeof import('./src/components/base/BasicComponents/BTabs.vue')['default']
    BTooltip: typeof import('./src/components/base/BasicComponents/BTooltip.vue')['default']
    BTree: typeof import('./src/components/base/BasicComponents/BTree.vue')['default']
    BUpload: typeof import('./src/components/base/BasicComponents/BUpload.vue')['default']
    CommonContainer: typeof import('./src/components/base/BasicComponents/CommonContainer.vue')['default']
    FormRenders: typeof import('./src/components/base/BasicComponents/BForm/FormRenders.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
