/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ACheckboxGroup: typeof import('ant-design-vue/es')['CheckboxGroup']
    AConfigProvider: typeof import('ant-design-vue/es')['ConfigProvider']
    ADropdown: typeof import('ant-design-vue/es')['Dropdown']
    AEmpty: typeof import('ant-design-vue/es')['Empty']
    AForm: typeof import('ant-design-vue/es')['Form']
    AFormItem: typeof import('ant-design-vue/es')['FormItem']
    AInput: typeof import('ant-design-vue/es')['Input']
    AMenu: typeof import('ant-design-vue/es')['Menu']
    AMenuItem: typeof import('ant-design-vue/es')['MenuItem']
    APagination: typeof import('ant-design-vue/es')['Pagination']
    ASelect: typeof import('ant-design-vue/es')['Select']
    ATable: typeof import('ant-design-vue/es')['Table']
    ATooltip: typeof import('ant-design-vue/es')['Tooltip']
    ATransfer: typeof import('ant-design-vue/es')['Transfer']
    BAlert: typeof import('./src/components/BasicComponents/BModal/BAlert.vue')['default']
    BButton: typeof import('./src/components/BasicComponents/BButton/BButton.vue')['default']
    BCard: typeof import('./src/components/BasicComponents/BCard/BCard.vue')['default']
    BCheckbox: typeof import('./src/components/BasicComponents/BCheckbox/BCheckbox.vue')['default']
    BForm: typeof import('./src/components/BasicComponents/BForm/BForm.vue')['default']
    BInput: typeof import('./src/components/BasicComponents/BInput/BInput.vue')['default']
    BList: typeof import('./src/components/BasicComponents/BList/BList.vue')['default']
    BLoading: typeof import('./src/components/BasicComponents/BLoading/BLoading.vue')['default']
    BModal: typeof import('./src/components/BasicComponents/BModal/BModal.vue')['default']
    BRadio: typeof import('./src/components/BasicComponents/BRadio/BRadio.vue')['default']
    BSelect: typeof import('./src/components/BasicComponents/BSelect/BSelect.vue')['default']
    BSpace: typeof import('./src/components/BasicComponents/BSpace/BSpace.vue')['default']
    BTabs: typeof import('./src/components/BasicComponents/BTabs/BTabs.vue')['default']
    BTooltip: typeof import('./src/components/BasicComponents/BTooltip/BTooltip.vue')['default']
    BTree: typeof import('./src/components/BasicComponents/BTree/BTree.vue')['default']
    BUpload: typeof import('./src/components/BasicComponents/BUpload/BUpload.vue')['default']
    FormRenders: typeof import('./src/components/BasicComponents/BForm/FormRenders.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
