name: 打包前端并部署到服务器
on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:

      - name: 读取仓库内容
        uses: actions/checkout@master

      - name: 安装nodejs
        uses: actions/setup-node@master

      - name: 安装依赖
        run: npm install
      - name: 打包
        run: npm run build
      - name: 复制dist文件with scp
        uses: nogsantos/ssh-scp-deploy@v1.3.0
        with:
          src: "dist/"
          host: ${{ secrets.HOST }}
          remote: ${{ secrets.TARGET }}
          port: ${{ secrets.PORT }}
          user: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}


##        uses: appleboy/scp-action@v0.0.1
#        with:
#          host: ${{ secrets.HOST }}
#          username: ${{ secrets.USERNAME }}
#          password: ${{ secrets.PASSWORD }}
#          port: ${{ secrets.PORT }}
#          source: "dist/"
#          target: ${{ secrets.TARGET }}